name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.image_name.outputs.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test container
        run: docker build --target test -t test-image .

      - name: Run linter
        run: docker run --rm test-image ruff check .

      - name: Run unit tests
        run: docker run --rm test-image pytest

      - name: Set image name for later jobs
        id: image_name
        run: echo "name=fastapi-test-app:${{ github.sha }}" >> $GITHUB_OUTPUT

  security-gate:
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build final application image
        run: docker build --target final -t ${{ needs.quality-gate.outputs.image_name }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'image'
          image-ref: ${{ needs.quality-gate.outputs.image_name }}
          format: 'sarif'
          output: 'trivy-image-report.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          scanners: 'vuln,secret'

      - name: Upload Trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-image-report.sarif'
